// movies
export const API_GET_MOVIES = 'API_GET_MOVIES'
export const API_POST_MOVIES = 'API_POST_MOVIES'
export const API_DELETE_MOVIES = 'API_DELETE_MOVIES'
export const API_PATCH_MOVIES = 'API_PATCH_MOVIES'
export const API_DETACH_MOVIES = 'API_DETACH_MOVIES'
export const API_APPEND_MOVIES = 'API_APPEND_MOVIES'


// actos
export const API_GET_ACTORS = 'API_GET_ACTORS'
export const API_DETACH_ACTORS = 'API_DETACH_ACTORS'
export const API_APPEND_ACTORS = 'API_APPEND_ACTORS'